### ISSUE TITLE
Add maven compilation

### ISSUE THREAD

**Issue by Downchuck** [openrq-team/OpenRQ#2]
Though ant is wonderful, it'd be nice to have maven support for building and distributing this library.

**Comment by redjaguar** [comment]
If you are still looking for Maven support I have forked the repo and moved it to a Maven build structure here: https://github.com/redjaguar/OpenRQ

**Comment by ruckc** [comment]
I also started going down this path, but got hung up on how to handle the
JMH performance tests.

**Comment by zemasa** [comment]
@redjaguar if you have it working and testing, we'd be happy to look at a pull request, possibly an alternative branch.
