### ISSUE TITLE
How to make it work in C#

### ISSUE THREAD

**Issue by matthew-a-thomas** [openrq-team/OpenRQ#3]
I was quite pleased to find you can use IKVM to convert this into a C# .Net dll, as long as you compile with Java <= 1.7

http://www.ikvm.net/userguide/ikvmc.html

P.S. Sorry if this isn't the best place to post this news; I just wanted it out there and in a place that Google/people might notice because it took me time to discover. Maybe this info could be placed in the readme, or on the wiki?

**Comment by matthew-a-thomas** [comment]
Here are the exact steps I took to get this into Visual Studio 2012:
<ol>
<li>Import OpenRQ into Eclipse. Make sure you get package names to line up with how the files land in your Eclipse project</li>
<li>Set the Eclipse project to use JRE/JDK 1.7. Simply setting the compliance level in build settings didn't seem to cut it, but I had to install JDK 1.7 and configure the Eclipse project to use it instead of 1.8</li>
<li>Export from Eclipse as a Jar. The export settings don't seem to matter much</li>
<li>Run IKVMC: "ikvmc -out:OpenRQ.dll -target:library -OpenRQ.jar". You'll get "class format error" warnings if you compiled with Java > 1.7</li>
<li>Add the generated .dll as a reference to your Visual Studio .Net project</li>
<li>...</li>
<li>Profit!</li>
</ol>

**Comment by rjpfonseca** [comment]
Thank you, Matthew.

To make things easier, I updated the target version of the jar files in the latest releases to 1.7. This way, you can skip to step 4 after downloading the updated jar file in https://github.com/openrq-team/OpenRQ/releases/latest

The updates are also in the build file of the master branch.

**Comment by matthew-a-thomas** [comment]
Great! I also discovered that IKVM (including the IKVMC binary) is more up-to-date in Nuget than on their website, and it's also necessary to reference a lot of IKVM DLLs to make it work, so people going this route will want to just get IKVM from Nuget and try using the IKVMC binary from there instead of downloading from their website. You might then be able to use Java 8, and it'll save time wiring your C# project together.
