### ISSUE TITLE
How to use OpenRQ

### ISSUE THREAD

**Issue by m8710200** [openrq-team/OpenRQ#7]
I'm download the openrq-3.3.2.jar  ,but  I don't know how to  use it?

Could somebody help me? Thanks!

I have setting the path!

In the cmd: 

java -cp.openrq-3.3.2.jar

you can see the problem:

Unrecognized option: -cp.openrq-3.3.2.jar
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by zemasa** [comment]
Not a project issue. Please refer to our wiki for examples on how to use OpenRQ and also the Java manual as that is a problem with your command.

**Comment by m8710200** [comment]
ok! I will try it again! thanks!

2016-08-14 1:06 GMT+08:00 Jose Lopes <notifications@github.com>:
